from test_fena.test_common import test_cmd

def test_scoreboards():
    test_cmd("@s _ti = players _ti2",       "scoreboard players operation @s fena.ti = players fena.ti2")
    test_cmd("@s _ti = @r _ti2",            "scoreboard players operation @s fena.ti = @r fena.ti2")
    test_cmd("@s _ti = 3",                  "scoreboard players set @s fena.ti 3")
    test_cmd(r"@s _ti = 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti = players _ti2",   "scoreboard players operation target fena.ti = players fena.ti2")
    test_cmd("target _ti = @r _ti2",        "scoreboard players operation target fena.ti = @r fena.ti2")
    test_cmd("target _ti = 3",              "scoreboard players set target fena.ti 3")
    test_cmd(r"target _ti = 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti = players _ti2", "scoreboard players operation setblock fena.ti = players fena.ti2")
    test_cmd("setblock _ti = @r _ti2",      "scoreboard players operation setblock fena.ti = @r fena.ti2")
    test_cmd("setblock _ti = 3",            "scoreboard players set setblock fena.ti 3")
    test_cmd(r"setblock _ti = 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti = players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti = @r fena.ti2")
    test_cmd("scoreboard players set @s fena.ti 3")
    test_cmd("scoreboard players operation target fena.ti = players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti = @r fena.ti2")
    test_cmd("scoreboard players set target fena.ti 3")
    test_cmd("scoreboard players operation setblock fena.ti = players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti = @r fena.ti2")
    test_cmd("scoreboard players set setblock fena.ti 3")

    test_cmd("@s _ti += players _ti2",       "scoreboard players operation @s fena.ti += players fena.ti2")
    test_cmd("@s _ti += @r _ti2",            "scoreboard players operation @s fena.ti += @r fena.ti2")
    test_cmd("@s _ti += 3",                  "scoreboard players add @s fena.ti 3")
    test_cmd(r"@s _ti += 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti += players _ti2",   "scoreboard players operation target fena.ti += players fena.ti2")
    test_cmd("target _ti += @r _ti2",        "scoreboard players operation target fena.ti += @r fena.ti2")
    test_cmd("target _ti += 3",              "scoreboard players add target fena.ti 3")
    test_cmd(r"target _ti += 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti += players _ti2", "scoreboard players operation setblock fena.ti += players fena.ti2")
    test_cmd("setblock _ti += @r _ti2",      "scoreboard players operation setblock fena.ti += @r fena.ti2")
    test_cmd("setblock _ti += 3",            "scoreboard players add setblock fena.ti 3")
    test_cmd(r"setblock _ti += 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti += players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti += @r fena.ti2")
    test_cmd("scoreboard players add @s fena.ti 3")
    test_cmd("scoreboard players operation target fena.ti += players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti += @r fena.ti2")
    test_cmd("scoreboard players add target fena.ti 3")
    test_cmd("scoreboard players operation setblock fena.ti += players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti += @r fena.ti2")
    test_cmd("scoreboard players add setblock fena.ti 3")

    test_cmd("@s _ti -= players _ti2",       "scoreboard players operation @s fena.ti -= players fena.ti2")
    test_cmd("@s _ti -= @r _ti2",            "scoreboard players operation @s fena.ti -= @r fena.ti2")
    test_cmd("@s _ti -= 3",                  "scoreboard players remove @s fena.ti 3")
    test_cmd(r"@s _ti -= 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti -= players _ti2",   "scoreboard players operation target fena.ti -= players fena.ti2")
    test_cmd("target _ti -= @r _ti2",        "scoreboard players operation target fena.ti -= @r fena.ti2")
    test_cmd("target _ti -= 3",              "scoreboard players remove target fena.ti 3")
    test_cmd(r"target _ti -= 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti -= players _ti2", "scoreboard players operation setblock fena.ti -= players fena.ti2")
    test_cmd("setblock _ti -= @r _ti2",      "scoreboard players operation setblock fena.ti -= @r fena.ti2")
    test_cmd("setblock _ti -= 3",            "scoreboard players remove setblock fena.ti 3")

    test_cmd("scoreboard players operation @s fena.ti -= players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti -= @r fena.ti2")
    test_cmd("scoreboard players remove @s fena.ti 3")
    test_cmd("scoreboard players operation target fena.ti -= players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti -= @r fena.ti2")
    test_cmd("scoreboard players remove target fena.ti 3")
    test_cmd("scoreboard players operation setblock fena.ti -= players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti -= @r fena.ti2")
    test_cmd("scoreboard players remove setblock fena.ti 3")

    test_cmd("@s _ti *= players _ti2",       "scoreboard players operation @s fena.ti *= players fena.ti2")
    test_cmd("@s _ti *= @r _ti2",            "scoreboard players operation @s fena.ti *= @r fena.ti2")
    test_cmd("@s _ti *= 3",                  "scoreboard players operation @s fena.ti *= 3 g.number")
    test_cmd(r"@s _ti *= 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti *= players _ti2",   "scoreboard players operation target fena.ti *= players fena.ti2")
    test_cmd("target _ti *= @r _ti2",        "scoreboard players operation target fena.ti *= @r fena.ti2")
    test_cmd("target _ti *= 3",              "scoreboard players operation target fena.ti *= 3 g.number")
    test_cmd(r"target _ti *= 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti *= players _ti2", "scoreboard players operation setblock fena.ti *= players fena.ti2")
    test_cmd("setblock _ti *= @r _ti2",      "scoreboard players operation setblock fena.ti *= @r fena.ti2")
    test_cmd("setblock _ti *= 3",            "scoreboard players operation setblock fena.ti *= 3 g.number")
    test_cmd(r"setblock _ti *= 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti *= players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti *= @r fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti *= 3 g.number")
    test_cmd("scoreboard players operation target fena.ti *= players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti *= @r fena.ti2")
    test_cmd("scoreboard players operation target fena.ti *= 3 g.number")
    test_cmd("scoreboard players operation setblock fena.ti *= players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti *= @r fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti *= 3 g.number")

    test_cmd("@s _ti /= players _ti2",       "scoreboard players operation @s fena.ti /= players fena.ti2")
    test_cmd("@s _ti /= @r _ti2",            "scoreboard players operation @s fena.ti /= @r fena.ti2")
    test_cmd("@s _ti /= 3",                  "scoreboard players operation @s fena.ti /= 3 g.number")
    test_cmd(r"@s _ti /= 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti /= players _ti2",   "scoreboard players operation target fena.ti /= players fena.ti2")
    test_cmd("target _ti /= @r _ti2",        "scoreboard players operation target fena.ti /= @r fena.ti2")
    test_cmd("target _ti /= 3",              "scoreboard players operation target fena.ti /= 3 g.number")
    test_cmd(r"target _ti /= 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti /= players _ti2", "scoreboard players operation setblock fena.ti /= players fena.ti2")
    test_cmd("setblock _ti /= @r _ti2",      "scoreboard players operation setblock fena.ti /= @r fena.ti2")
    test_cmd("setblock _ti /= 3",            "scoreboard players operation setblock fena.ti /= 3 g.number")
    test_cmd(r"setblock _ti /= 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti /= players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti /= @r fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti /= 3 g.number")
    test_cmd("scoreboard players operation target fena.ti /= players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti /= @r fena.ti2")
    test_cmd("scoreboard players operation target fena.ti /= 3 g.number")
    test_cmd("scoreboard players operation setblock fena.ti /= players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti /= @r fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti /= 3 g.number")

    test_cmd("@s _ti %= players _ti2",       "scoreboard players operation @s fena.ti %= players fena.ti2")
    test_cmd("@s _ti %= @r _ti2",            "scoreboard players operation @s fena.ti %= @r fena.ti2")
    test_cmd("@s _ti %= 3",                  "scoreboard players operation @s fena.ti %= 3 g.number")
    test_cmd(r"@s _ti %= 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti %= players _ti2",   "scoreboard players operation target fena.ti %= players fena.ti2")
    test_cmd("target _ti %= @r _ti2",        "scoreboard players operation target fena.ti %= @r fena.ti2")
    test_cmd("target _ti %= 3",              "scoreboard players operation target fena.ti %= 3 g.number")
    test_cmd(r"target _ti %= 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti %= players _ti2", "scoreboard players operation setblock fena.ti %= players fena.ti2")
    test_cmd("setblock _ti %= @r _ti2",      "scoreboard players operation setblock fena.ti %= @r fena.ti2")
    test_cmd("setblock _ti %= 3",            "scoreboard players operation setblock fena.ti %= 3 g.number")
    test_cmd(r"setblock _ti %= 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti %= players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti %= @r fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti %= 3 g.number")
    test_cmd("scoreboard players operation target fena.ti %= players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti %= @r fena.ti2")
    test_cmd("scoreboard players operation target fena.ti %= 3 g.number")
    test_cmd("scoreboard players operation setblock fena.ti %= players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti %= @r fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti %= 3 g.number")

    test_cmd("@s _ti <= players _ti2",       "scoreboard players operation @s fena.ti < players fena.ti2")
    test_cmd("@s _ti <= @r _ti2",            "scoreboard players operation @s fena.ti < @r fena.ti2")
    test_cmd("@s _ti <= 3",                  "scoreboard players operation @s fena.ti < 3 g.number")
    test_cmd(r"@s _ti <= 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti <= players _ti2",   "scoreboard players operation target fena.ti < players fena.ti2")
    test_cmd("target _ti <= @r _ti2",        "scoreboard players operation target fena.ti < @r fena.ti2")
    test_cmd("target _ti <= 3",              "scoreboard players operation target fena.ti < 3 g.number")
    test_cmd(r"target _ti <= 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti <= players _ti2", "scoreboard players operation setblock fena.ti < players fena.ti2")
    test_cmd("setblock _ti <= @r _ti2",      "scoreboard players operation setblock fena.ti < @r fena.ti2")
    test_cmd("setblock _ti <= 3",            "scoreboard players operation setblock fena.ti < 3 g.number")
    test_cmd(r"setblock _ti <= 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti < players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti < @r fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti < 3 g.number")
    test_cmd("scoreboard players operation target fena.ti < players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti < @r fena.ti2")
    test_cmd("scoreboard players operation target fena.ti < 3 g.number")
    test_cmd("scoreboard players operation setblock fena.ti < players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti < @r fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti < 3 g.number")

    test_cmd("@s _ti >= players _ti2",       "scoreboard players operation @s fena.ti > players fena.ti2")
    test_cmd("@s _ti >= @r _ti2",            "scoreboard players operation @s fena.ti > @r fena.ti2")
    test_cmd("@s _ti >= 3",                  "scoreboard players operation @s fena.ti > 3 g.number")
    test_cmd(r"@s _ti >= 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti >= players _ti2",   "scoreboard players operation target fena.ti > players fena.ti2")
    test_cmd("target _ti >= @r _ti2",        "scoreboard players operation target fena.ti > @r fena.ti2")
    test_cmd("target _ti >= 3",              "scoreboard players operation target fena.ti > 3 g.number")
    test_cmd(r"target _ti >= 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti >= players _ti2", "scoreboard players operation setblock fena.ti > players fena.ti2")
    test_cmd("setblock _ti >= @r _ti2",      "scoreboard players operation setblock fena.ti > @r fena.ti2")
    test_cmd("setblock _ti >= 3",            "scoreboard players operation setblock fena.ti > 3 g.number")
    test_cmd(r"setblock _ti >= 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti > players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti > @r fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti > 3 g.number")
    test_cmd("scoreboard players operation target fena.ti > players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti > @r fena.ti2")
    test_cmd("scoreboard players operation target fena.ti > 3 g.number")
    test_cmd("scoreboard players operation setblock fena.ti > players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti > @r fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti > 3 g.number")

    test_cmd("@s _ti swap players _ti2",       "scoreboard players operation @s fena.ti >< players fena.ti2")
    test_cmd("@s _ti swap @r _ti2",            "scoreboard players operation @s fena.ti >< @r fena.ti2")
    test_cmd("@s _ti swap 3",                  expect_error=True)
    test_cmd(r"@s _ti swap 3 {Nbt:1b}",        expect_error=True)
    test_cmd("target _ti swap players _ti2",   "scoreboard players operation target fena.ti >< players fena.ti2")
    test_cmd("target _ti swap @r _ti2",        "scoreboard players operation target fena.ti >< @r fena.ti2")
    test_cmd("target _ti swap 3",              expect_error=True)
    test_cmd(r"target _ti swap 3 {Nbt:1b}",    expect_error=True)
    test_cmd("setblock _ti swap players _ti2", "scoreboard players operation setblock fena.ti >< players fena.ti2")
    test_cmd("setblock _ti swap @r _ti2",      "scoreboard players operation setblock fena.ti >< @r fena.ti2")
    test_cmd("setblock _ti swap 3",            expect_error=True)
    test_cmd(r"setblock _ti swap 3 {Nbt:1b}",  expect_error=True)

    test_cmd("scoreboard players operation @s fena.ti >< players fena.ti2")
    test_cmd("scoreboard players operation @s fena.ti >< @r fena.ti2")
    test_cmd("scoreboard players operation target fena.ti >< players fena.ti2")
    test_cmd("scoreboard players operation target fena.ti >< @r fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti >< players fena.ti2")
    test_cmd("scoreboard players operation setblock fena.ti >< @r fena.ti2")

    test_cmd("@s reset _ti",        "scoreboard players reset fena.ti @s")
    test_cmd("target reset _ti",    "scoreboard players reset fena.ti target")
    test_cmd("setblock reset _ti",  "scoreboard players reset fena.ti setblock")
    test_cmd("scoreboard players reset fena.ti @s")
    test_cmd("scoreboard players reset fena.ti target")
    test_cmd("scoreboard players reset fena.ti setblock")

    test_cmd("@s enable _ti",       "scoreboard players enable fena.ti @s")
    test_cmd("target enable _ti",   "scoreboard players enable fena.ti target")
    test_cmd("setblock enable _ti", "scoreboard players enable fena.ti setblock")
    test_cmd("scoreboard players enable fena.ti @s")
    test_cmd("scoreboard players enable fena.ti target")
    test_cmd("scoreboard players enable fena.ti setblock")

    test_cmd("@s <- _ti",           "scoreboard players get fena.ti @s")
    test_cmd("target <- _ti",       "scoreboard players get fena.ti target")
    test_cmd("setblock <- _ti",     "scoreboard players get fena.ti setblock")
    test_cmd("scoreboard players get fena.ti @s")
    test_cmd("scoreboard players get fena.ti target")
    test_cmd("scoreboard players get fena.ti setblock")
