from test_fena.test_common import test_vec2, test_vec3, test_coord

def test_coords():
    test_coord("1")
    test_coord("1.5")
    test_coord("-1")
    test_coord("-1.5")
    test_coord("1e1", expect_error=True)
    test_coord("1.5e1", expect_error=True)
    test_coord("-1E1", expect_error=True)
    test_coord("-1.5E1", expect_error=True)

    test_coord("^1")
    test_coord("^1.5")
    test_coord("^-1")
    test_coord("^-1.5")
    test_coord("^1e1", expect_error=True)
    test_coord("^1.5e1", expect_error=True)
    test_coord("^-1E1", expect_error=True)
    test_coord("^-1.5E1", expect_error=True)

    test_coord("~1")
    test_coord("~1.5")
    test_coord("~-1")
    test_coord("~-1.5")
    test_coord("~1e1", expect_error=True)
    test_coord("~1.5e1", expect_error=True)
    test_coord("~-1E1", expect_error=True)
    test_coord("~-1.5E1", expect_error=True)

    test_vec2("~ ~")
    test_vec2("^ ^", expect_error=True)
    test_vec2("~1 ~2")
    test_vec2("~1 2")
    test_vec2("~-1 -2")
    test_vec2("-1 -2")
    test_vec2("~.1 ~")
    test_vec2("~1.1 ~2")
    test_vec2("~1 2.1")
    test_vec2("~-1 -2.1")
    test_vec2("-1 -2")
    test_vec2("^-1 ^-2", expect_error=True)

    test_vec3("~ ~ ~")
    test_vec3("^ ^ ^")
    test_vec3("~1 ~2 ~3")
    test_vec3("~1 2 ~3")
    test_vec3("~-1 -2 ~3")
    test_vec3("-1 -2 3")
    test_vec3("~.1 ~ ~")
    test_vec3("~1.1 ~2 ~3")
    test_vec3("~1 2.1 ~3")
    test_vec3("~-1 -2.1 ~3")
    test_vec3("-1 -2 3.1")
    test_vec3("^-1 ^-2 ^3.1")

    test_vec3("1 2 ^3", expect_error=True)
    test_vec3("~1 2 ^3", expect_error=True)
    test_vec3("~1 ~2 ^3", expect_error=True)
    test_vec3("-1 -2 3.1e5", expect_error=True)
    test_vec3("-1 -2e5 3.1", expect_error=True)
    test_vec3("-2 3.1", expect_error=True)
