from test_fena.test_common import test_block

def test_blocks():
    # block states as simple values
    test_block("stonebrick[0]",  "minecraft:stonebrick 0")
    test_block("stonebrick[1]",  "minecraft:stonebrick 1")
    test_block("stonebrick[-1]", "minecraft:stonebrick -1")
    test_block("stonebrick[*]",  "minecraft:stonebrick *")
    test_block("stonebrick[]",   "minecraft:stonebrick *")
    test_block("stonebrick",     "minecraft:stonebrick *")
    test_block("minecraft:stonebrick[0]",  "minecraft:stonebrick 0")
    test_block("minecraft:stonebrick[1]",  "minecraft:stonebrick 1")
    test_block("minecraft:stonebrick[-1]", "minecraft:stonebrick -1")
    test_block("minecraft:stonebrick[*]",  "minecraft:stonebrick *")
    test_block("minecraft:stonebrick[]",   "minecraft:stonebrick *")
    test_block("minecraft:stonebrick",     "minecraft:stonebrick *")

    # actual block states
    test_block("stonebrick[variant=mossy_stonebrick]",               "minecraft:stonebrick variant=mossy_stonebrick")
    test_block("stone_brick_stairs[facing=south,half=top]",          "minecraft:stone_brick_stairs facing=south,half=top")
    test_block("stone_brick_stairs[facing=south, half=top]",         "minecraft:stone_brick_stairs facing=south,half=top")
    test_block("stone_brick_stairs[facing = south, half = top]",     "minecraft:stone_brick_stairs facing=south,half=top")
    test_block("stone_brick_stairs [ facing = south, half = top ] ", "minecraft:stone_brick_stairs facing=south,half=top")
    test_block("minecraft:stonebrick[variant=mossy_stonebrick]",               "minecraft:stonebrick variant=mossy_stonebrick")
    test_block("minecraft:stone_brick_stairs[facing=south,half=top]",          "minecraft:stone_brick_stairs facing=south,half=top")
    test_block("minecraft:stone_brick_stairs[facing=south, half=top]",         "minecraft:stone_brick_stairs facing=south,half=top")
    test_block("minecraft:stone_brick_stairs[facing = south, half = top]",     "minecraft:stone_brick_stairs facing=south,half=top")
    test_block("minecraft:stone_brick_stairs [ facing = south, half = top ] ", "minecraft:stone_brick_stairs facing=south,half=top")

    # nbt tags
    test_block(r'chest[0]{}',  r'minecraft:chest 0 replace {}')
    test_block(r'chest[1]{}',  r'minecraft:chest 1 replace {}')
    test_block(r'chest[-1]{}', r'minecraft:chest -1 replace {}')
    test_block(r'chest[*]{}',  r'minecraft:chest * replace {}')
    test_block(r'chest[]{}',   r'minecraft:chest * replace {}')
    test_block(r'chest{}',     r'minecraft:chest * replace {}')
    test_block(r'minecraft:chest[0]',  r'minecraft:chest 0')
    test_block(r'minecraft:chest[1]',  r'minecraft:chest 1')
    test_block(r'minecraft:chest[-1]', r'minecraft:chest -1')
    test_block(r'minecraft:chest[*]',  r'minecraft:chest *')
    test_block(r'minecraft:chest[]',   r'minecraft:chest *')
    test_block(r'minecraft:chest',     r'minecraft:chest *')

    test_block(r'chest[facing=west]{}',                     r'minecraft:chest facing=west replace {}')
    test_block(r'chest[facing=west]{Lock:"lol"}',           r'minecraft:chest facing=west replace {Lock:"lol"}')
    test_block(r'minecraft:chest[facing=west]{}',           r'minecraft:chest facing=west replace {}')
    test_block(r'minecraft:chest[facing=west]{Lock:"lol"}', r'minecraft:chest facing=west replace {Lock:"lol"}')

    test_block(r'chest[0]{Lock:"lol"}',  r'minecraft:chest 0 replace {Lock:"lol"}')
    test_block(r'chest[1]{Lock:"lol"}',  r'minecraft:chest 1 replace {Lock:"lol"}')
    test_block(r'chest[-1]{Lock:"lol"}', r'minecraft:chest -1 replace {Lock:"lol"}')
    test_block(r'chest[*]{Lock:"lol"}',  r'minecraft:chest * replace {Lock:"lol"}')
    test_block(r'chest[]{Lock:"lol"}',   r'minecraft:chest * replace {Lock:"lol"}')
    test_block(r'chest{Lock:"lol"}',     r'minecraft:chest * replace {Lock:"lol"}')
    test_block(r'minecraft:chest[0]{Lock:"lol"}',  r'minecraft:chest 0 replace {Lock:"lol"}')
    test_block(r'minecraft:chest[1]{Lock:"lol"}',  r'minecraft:chest 1 replace {Lock:"lol"}')
    test_block(r'minecraft:chest[-1]{Lock:"lol"}', r'minecraft:chest -1 replace {Lock:"lol"}')
    test_block(r'minecraft:chest[*]{Lock:"lol"}',  r'minecraft:chest * replace {Lock:"lol"}')
    test_block(r'minecraft:chest[]{Lock:"lol"}',   r'minecraft:chest * replace {Lock:"lol"}')
    test_block(r'minecraft:chest{Lock:"lol"}',     r'minecraft:chest * replace {Lock:"lol"}')

    # errors
    test_block('not_a_block', expect_error=True)
    test_block("wrong_id:stonebrick", expect_error=True)
    test_block("stonebrick:stonebrick", expect_error=True)

    test_block('stonebrick[0,1]', expect_error=True)
    test_block('stonebrick[0=0,1=1]', expect_error=True)
    test_block('stonebrick[asdf=0,nou=1]', expect_error=True)
    test_block("stone_brick_stairs[=]", expect_error=True)
    test_block("stone_brick_stairs[facing]", expect_error=True)
    test_block("stone_brick_stairs[facing=]", expect_error=True)
    test_block("stone_brick_stairs[facing=south=north]", expect_error=True)
    test_block("stone_brick_stairs[facing=south half=top]", expect_error=True)

    test_block('minecraft:not_a_block', expect_error=True)
    test_block('minecraft:stonebrick[0,1]', expect_error=True)
    test_block('minecraft:stonebrick[0=0,1=1]', expect_error=True)
    test_block('minecraft:stonebrick[asdf=0,nou=1]', expect_error=True)
    test_block("minecraft:stone_brick_stairs[=]", expect_error=True)
    test_block("minecraft:stone_brick_stairs[facing]", expect_error=True)
    test_block("minecraft:stone_brick_stairs[facing=]", expect_error=True)
    test_block("minecraft:stone_brick_stairs[facing=south=north]", expect_error=True)
    test_block("minecraft:stone_brick_stairs[facing=south half=top]", expect_error=True)
